// Gpio.c
#include "Gpio.h"

void GpioInit(void)
{
	// ENTRADAS
	GPIO_Init(ENTRADA_4_PIN,GPIO_MODE_IN_FL_NO_IT);
	GPIO_Init(ENTRADA_5_PIN,GPIO_MODE_IN_FL_NO_IT);
	GPIO_Init(ENTRADA_6_PIN,GPIO_MODE_IN_FL_NO_IT);
	GPIO_Init(ENTRADA_7_PIN,GPIO_MODE_IN_FL_NO_IT);
	GPIO_Init(ENTRADA_8_PIN,GPIO_MODE_IN_FL_NO_IT);
	GPIO_Init(TECLA_PIN,GPIO_MODE_IN_FL_NO_IT);
	
	// SAIDAS
	GPIO_Init(SAIDA_1,GPIO_MODE_OUT_PP_LOW_SLOW);
	GPIO_Init(SAIDA_2,GPIO_MODE_OUT_PP_LOW_SLOW);
	GPIO_Init(SAIDA_3,GPIO_MODE_OUT_PP_LOW_SLOW);
	GPIO_Init(CONFIG_ENTRADA_8,GPIO_MODE_OUT_PP_LOW_SLOW);
	GPIO_Init(CD1,GPIO_MODE_OUT_PP_LOW_SLOW);
	GPIO_Init(CD2,GPIO_MODE_OUT_PP_LOW_SLOW);
	GPIO_Init(CD3,GPIO_MODE_OUT_PP_LOW_SLOW);
	GPIO_Init(CD4,GPIO_MODE_OUT_PP_LOW_SLOW);
	GPIO_Init(SEG_A,GPIO_MODE_OUT_PP_LOW_SLOW);
	GPIO_Init(SEG_B,GPIO_MODE_OUT_PP_LOW_SLOW);
	GPIO_Init(SEG_C,GPIO_MODE_OUT_PP_LOW_SLOW);
	GPIO_Init(SEG_D,GPIO_MODE_OUT_PP_LOW_SLOW);
	GPIO_Init(SEG_E,GPIO_MODE_OUT_PP_LOW_SLOW);
	GPIO_Init(SEG_F,GPIO_MODE_OUT_PP_LOW_SLOW);
	GPIO_Init(SEG_G,GPIO_MODE_OUT_PP_LOW_SLOW);
	GPIO_Init(SEG_P,GPIO_MODE_OUT_PP_LOW_SLOW);
	
	CONFIG_ENT8_NEG;
}